# Generated by Django 6.0.6 on 2026-07-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orders_amount_orders_is_paid_orders_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='transaction_uuid',
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
    ]
